name: Release

on:
  push:
    tags:
      - 'v3.*.*'

jobs:
  release:
    runs-on: ubuntu-22.04
    env: 
      token: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/peaceiris/workflows/blob/main/create-release-npm/action.yml
      - name: Create release
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "See [CHANGELOG.md](https://github.com/${GITHUB_REPOSITORY}/blob/${TAG_NAME}/CHANGELOG.md) for more details." > ./release_notes.md
          RELEASE_TITLE="$(jq -r '.name' ./package.json) ${TAG_NAME}"
          gh release create "${TAG_NAME}" ${{ inputs.draft }} ${{ inputs.prerelease }} \
            --title "${RELEASE_TITLE}" \
            --notes-file ./release_notes.md
        shell: bash
